### ISSUE TITLE
Pressure advance rounded corners

### ISSUE THREAD

**Issue by EkiciLP** [AndrewEllis93/Print-Tuning-Guide#107]
Hey,

I have an Anycubic Vyper with direct extruder mod and wanted to calibrate it with your guide, which is, may I say, a life saver for people like me so thank you.
Im using Prusament recycled
But I ran into an issue when calibrate PA using Klipper.
For some reason the corners are rounded on all lines. I have attached a picture of my Test pattern.
![WhatsApp Image 2023-12-20 at 22 22 01](https://github.com/AndrewEllis93/Print-Tuning-Guide/assets/72763011/67264631-bd13-4988-9ad3-378dc1b34dba)

What can I do to fix that?

**Comment by dougshell** [comment]
A few things here. 
Recycled filament is never going to be as consistent as new filament, so keep that in mind. 
Additionally, this photo is not well-focused and is very compressed. It is difficult for anyone to give you advice when it is hard to see what is going on. 
You may want to cover a wider range when starting your testing such as from .01 to .08 with .005 increments as the guide indicates.
Finally, I don't think this is a proper place for troubleshooting your printer; rather, it should be used for issues with the guide itself. I would head to either the klipper or the prusa3d discord server (other-fdm section) and ask for help there.
