### ISSUE TITLE
Cura does have per object Extrusion Multiplier (Flow) settings.

### ISSUE THREAD

**Issue by atoomnetmarc** [AndrewEllis93/Print-Tuning-Guide#13]
Hi, I am following your guide and got confused by:
> Cura and Prusa Slicer do not have per object Extrusion Multiplier settings so each test cube will need to be printed separately.

You can configure a per model setting, it seems to me that this is what is needed for the EM calibration.

![afbeelding](https://user-images.githubusercontent.com/48124268/155860594-91fac3f1-b7d4-4abd-94cc-a657dbe86d66.png)

**Comment by AndrewEllis93** [comment]
> Hi, I am following your guide and got confused by:
> 
> > Cura and Prusa Slicer do not have per object Extrusion Multiplier settings so each test cube will need to be printed separately.
> 
> You can configure a per model setting, it seems to me that this is what is needed for the EM calibration.
> 
> ![afbeelding](https://user-images.githubusercontent.com/48124268/155860594-91fac3f1-b7d4-4abd-94cc-a657dbe86d66.png)

Ah, was just what I was told, I don't use Cura very often (or maybe was changed, not sure)

Regardless, I added a screenshot, commit 1cf5634eca16c3f74acd1377a9177298ac4199f6. 

Do you
