### ISSUE TITLE
Consider additional to layer shifting section

### ISSUE THREAD

**Issue by johnssarris** [AndrewEllis93/Print-Tuning-Guide#14]
Under: Troubleshooting > Layer Shifting > Mechanical

Consider adding detail about checking drive pulley setscrew. It took me ages to track down a stupid setscrew that was just loose enough to cause layer shifts after some direction changes.

**Comment by AndrewEllis93** [comment]
Will do.

**Comment by AndrewEllis93** [comment]
Added
