### ISSUE TITLE
Final G28 after BED_MESH_CALIBRATE?

### ISSUE THREAD

**Issue by msteele999** [AndrewEllis93/Print-Tuning-Guide#16]
Andrew,

Thank you for this excellent guide - I am utilizing it to get my printer (V2.4 300mm^3) ready for PIF service.

Quick question - I am adding BED_MESH_CALIBRATE to my workflow as well as heat soaking. Do I need to add a final G28 before I start printing?

e.g: heat soak --> BED_MESH_CLEAR --> G28 --> QUAD_GANTRY_LEVEL --> G28 --> BED_MESH_CALIBRATE -->  G28 --> print

Best regards,

Mark Steele - V2.2024

**Comment by AndrewEllis93** [comment]
It's important to have a G28 after the QGL (and to ensure it's done at temperature) but otherwise it's not needed. BED_MESH_CALIBRATE will not throw off your Z offset, so you don't have to G28 after.
