### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by Ataraksia** [AndrewEllis93/Print-Tuning-Guide#17]
This isn't an actual issue so you can close it after reading.

I just wanted to say well done.  Your guides in general have always been excellent, but I finally got around to going through your gantry squaring guide in particular, and it is exceptional.  I was just thinking to myself the other day how rare it is in the opensource community to find great instructions accompanying projects (through no fault of their own obviously; individuals contributing to such projects are already going above and beyond if they provide any sort of guide at all, not to mention writing good instructions often takes a very different skillset/mindset than what is required for actually working on the project itself).  Your own guide covered absolutely everything that was needed for the process in both text and image-based formats, and did so clearly and succinctly, without including anything that seemed superfluous.  I think the final step really exemplifies what I mean where you even had the consideration and forethought to include a reminder to change back the idle timeout.  It's a small thing, but it's the kind of detail that most guides gloss over.

Thank you for the fantastic work you do here :)

**Comment by AndrewEllis93** [comment]
Thank you, glad it's helping, and glad the little things aren't going unnoticed! :)
<3
