### ISSUE TITLE
fix Link to macro

### ISSUE THREAD

**Issue by Moulebutz** [AndrewEllis93/Print-Tuning-Guide#18]
https://github.com/AndrewEllis93/Print-Tuning-Guide/blob/11d9497f8347d642116d23c8dcac0613a3a204d7/articles/determining_max_speeds_accels.md?plain=1#L58

**Comment by AndrewEllis93** [comment]
Fixed, thanks! Knew I still had some broken links hiding somewhere after the reorganization.. :)
