### ISSUE TITLE
PrusaCode will not working

### ISSUE THREAD

**Issue by 4noxx** [AndrewEllis93/Print-Tuning-Guide#22]
latest version of PS

![image](https://user-images.githubusercontent.com/12627059/168382252-1fb70145-13b5-4ab4-ac5b-95120571fac9.png)

**Comment by AndrewEllis93** [comment]
Is the text just cut off at the end here, or is the end actually missing?

![image](https://user-images.githubusercontent.com/34943186/168390957-3b07b14d-2e85-4ca9-88d6-7279367841b1.png)

**Comment by AndrewEllis93** [comment]
Just tested this out, was able to reproduce the error.
Try this:
```
M104 S0 ; Stops PS/SS from sending temp waits separately
M140 S0
PRINT_START BED=[first_layer_bed_temperature] HOTEND=[first_layer_temperature[initial_extruder]]
```
