### ISSUE TITLE
TEST_SPEED macro accuracy issue with hall-effect endstop

### ISSUE THREAD

**Issue by linyongzheng** [AndrewEllis93/Print-Tuning-Guide#24]
If the carriage is too close to the hall effect endstop for the first homing, the microsteps can potentially be miscounted during the G28 sequence.

Might want to mention this potential issue in the work instructions or modify the macro to account for hall-effect endstop users.

**Comment by AndrewEllis93** [comment]
How do you mitigate this? I don't have a hall effect endstop, so I'm not too familiar with it. 

For the first homing sequence, would it be best to conditional home, move away 2cm or so, home again for the actual measurement, then report position?

**Comment by AndrewEllis93** [comment]
In the meantime, I added a note about hall effects endstops.

**Comment by linyongzheng** [comment]
I've been doing a conditional home, then move to center of bed before
homing to report position. I'm sure there are better ways to do this but it
has been working for me.

**Comment by AndrewEllis93** [comment]
I have modified the macro, can you please see if that helps and let me know?

**Comment by AndrewEllis93** [comment]
Modified the macro to move away before first measurement homing
