### ISSUE TITLE
FR: "Back to Table of Contents" on page bottom

### ISSUE THREAD

**Issue by Dingushippo** [AndrewEllis93/Print-Tuning-Guide#26]
It's a bit more natural to click the "Back to Table of Contents" link when you've finished reading the article, at the bottom. That way you wouldn't need to scroll all the way up to go back. It's not a big thing, but it would be a nice quality of life improvement

**Comment by AndrewEllis93** [comment]
Added ToC links to bottom in 93beaa5f7b9981d4aeeddbf8e9f6f38b67a8e077. 

[Kept the top ones too](https://c.tenor.com/EKu-P3ELIeEAAAAC/why-not-both-both.gif) :)
