### ISSUE TITLE
Twisted/skewed frame

### ISSUE THREAD

**Issue by dewi-ny-je** [AndrewEllis93/Print-Tuning-Guide#28]
Based on 
https://discord.com/channels/431557959978450984/582347488938164240/993958021283725433
showing an unusual bed mesh
![image](https://user-images.githubusercontent.com/2866139/177496644-1c26c694-24bf-41d3-a12a-2692a6a1b8a4.png)

and on the answers
https://discord.com/channels/431557959978450984/582347488938164240/994063694436782201
"Mesh looks like a twisted frame to me. Could the feet arrangement have changes. Try adjusting feet or shimming?"

https://discord.com/channels/431557959978450984/582347488938164240/994121022536175676
"Actually I remember the mesh was flatter when the printer was on a desk, then I moved it upstairs and placed on the floor"

which suggests a skewed/twisted/uneven frame, would it be possible to extend the page about gantry squaredness to a more general squaredness of the outer frame (even vertically), with tips to check and correct?
Of course it's less relevant for Vorons, since they have 4 point bed screws and a gantry independent from the outer frame, but your guide is very good and used also by people with different printers!

In the case of that post, the author with the issue has a glass bed so that can be used as reference, but given the photo posted, the gantry is using 8 mm rods so it will sag, making even a perfect frame show some bowing.

It's tricky, but maybe with your experience you can extend the guide by providing at least tips.
If you provide an example mesh with the issue, some people may even realise they are affected by it and take actions!

**Comment by AndrewEllis93** [comment]
Sorry been procrastinating this one purely because I don't know how exactly to approach it. There are a lot of different printers out there, so it's hard to give generalized advice for this.

**Comment by dewi-ny-je** [comment]
> Sorry been procrastinating this one purely because I don't know how exactly to approach it. There are a lot of different printers out there, so it's hard to give generalized advice for this.

I understand.
Maybe just mentioning that a mesh like the one I provided may be indicative of a skewed frame could be enough to make people aware so that they can check.
