### ISSUE TITLE
Retraction Test 45 degree bug

### ISSUE THREAD

**Issue by SirRenix** [AndrewEllis93/Print-Tuning-Guide#29]
![image](https://user-images.githubusercontent.com/7069603/182497446-6380bd5b-b3fe-42ba-a223-8247a5938eb0.png)
The picture says more than I can write. I have setup the profile according to the guide and this was one of the last steps.

**Comment by AndrewEllis93** [comment]
Probably just another fun SS bug. Try resetting this setting.

![image](https://user-images.githubusercontent.com/34943186/182514509-942c91ce-5d60-40b0-9b51-fe82aa87f6a9.png)

**Comment by SirRenix** [comment]
I figured that was the problem. I dont import your profile, 
I work through every step from your guide.
