### ISSUE TITLE
Determining Maximum Speeds and Accelerations

### ISSUE THREAD

**Issue by gknops** [AndrewEllis93/Print-Tuning-Guide#3]
Hi,

Thanks for your great guide!

I wonder if you could give a "safe" acceleration value to use when testing speed. I assume if the acceleration value is chosen too low, the maximum speed will never be reached depending on printer size?

**Comment by mUbsta** [comment]
It looks like https://github.com/AndrewEllis93/Print-Tuning-Guide/commit/604030ed3e879d166261403a614e1214bf428073 resolves this @gknops.

**Comment by AndrewEllis93** [comment]
Indeed, just added more detail around this (though it's a gazillion commits because I'm commit-happy). Closing!

**Comment by gknops** [comment]
Much appreciate your work, I have applied this guide to several printers now. Thank you!!!
