### ISSUE TITLE
Hi , i read your Print guide, great work, but 1 misstake

### ISSUE THREAD

**Issue by Kaicura** [AndrewEllis93/Print-Tuning-Guide#31]
hi, i read your print guide, it says that cura can't do PA. It has been able to do this with a plugin for 2 years. 
Here the Link to Cura Plugin for Pressure Advance :
https://github.com/ollyfg/cura_pressure_advance_setting

![image](https://user-images.githubusercontent.com/65878296/185707432-d46f381c-9409-4ba6-98c7-2b5483b6fa46.png)

**Comment by AndrewEllis93** [comment]
Thanks! I will make a note of this in the guide.

**Comment by AndrewEllis93** [comment]
Added Cura PA note in c64da858177ec1e50943be92d3334fec79fb0513
