### ISSUE TITLE
Determining Maximum Volumetric Flow Rate

### ISSUE THREAD

**Issue by jchidley** [AndrewEllis93/Print-Tuning-Guide#35]
Stefan, CNC Kitchen on YouTube, has [an excellent video](https://youtu.be/lBi0-NotcP0) that uses a tool he built for working out flow rates. One of his viewers translated that tool to a [web page](https://hotend-flow-tester.netlify.app/).

I needed to adjust the `[extruder] max_extrude_cross_section` klipper setting for the tests.

**Comment by AndrewEllis93** [comment]
Added a note about this.
