### ISSUE TITLE
Inconsistent Order of the first Print Tuning steps.

### ISSUE THREAD

**Issue by ebrithiljonas** [AndrewEllis93/Print-Tuning-Guide#41]
This is just a minor thing that I noticed while following your guide. 

On the main Readme it says this: "Essentials. Read/follow these in order shown." and then it shows the following things:
- [Build Surface Adhesion](https://github.com/AndrewEllis93/Print-Tuning-Guide/blob/main/articles/build_surface_adhesion.md)
- [First Layer Squish](https://github.com/AndrewEllis93/Print-Tuning-Guide/blob/main/articles/first_layer_squish.md)
- [Pressure Advance](https://github.com/AndrewEllis93/Print-Tuning-Guide/blob/main/articles/pressure_advance.md) ("Linear Advance" in Marlin)

And in the [Build Surface Adhesion](https://github.com/AndrewEllis93/Print-Tuning-Guide/blob/main/articles/build_surface_adhesion.md) guide it says right at the beginning to first ensure that the "First Layer Squish" is correct.

So wouldn't it make more sense to list the First Layer Squish Guide before the Build Surface Adhesion Guide in the main Readme?

**Comment by AndrewEllis93** [comment]
I have reformatted that page. I split it into prep/handling and then made a separate troubleshooting section.

The troubleshooting section now says:

> 💡 If this is your first time through this guide, skip to the next step - [📄first layer squish](https://file+.vscode-resource.vscode-cdn.net/articles/first_layer_squish.md).
> This section is just for further troubleshooting if you are still having issues.
