### ISSUE TITLE
No fan speed in new PA tuning tool

### ISSUE THREAD

**Issue by Allidoisowen** [AndrewEllis93/Print-Tuning-Guide#42]
Sliced two files. Both at 50% fan speed entered into the online form. 
Both files sliced with 0% fan speed.
Two M106 S0 commands found.

Line 94 and 514 in the attached gcode file.
Screenshot of settings used included.

[TheGoo_PA_Tune_003_004.txt](https://github.com/AndrewEllis93/Print-Tuning-Guide/files/10080794/TheGoo_PA_Tune_003_004.txt)
[TheGoo_PA_Tune.txt](https://github.com/AndrewEllis93/Print-Tuning-Guide/files/10080795/TheGoo_PA_Tune.txt)
![2022-11-23 22_16_52-Ellis' Pressure Advance _ Linear Advance Calibration Tool](https://user-images.githubusercontent.com/87401458/203693921-a5e826c7-895d-4500-8527-8ae2b800f0ca.png)
![2022-11-23 22_16_34-Ellis' Pressure Advance _ Linear Advance Calibration Tool](https://user-images.githubusercontent.com/87401458/203693925-16e19d49-c468-42f6-9875-8df332bef16b.png)

**Comment by AndrewEllis93** [comment]
Thanks for the report! [Just fixed.](https://github.com/AndrewEllis93/andrewellis93.github.io/commit/e82613518d824381b2c8eeb38b7a1b4bc6131e85)
