### ISSUE TITLE
Pressure Advance Calibration tool

### ISSUE THREAD

**Issue by pki791** [AndrewEllis93/Print-Tuning-Guide#44]
The tool is very good, there is one small issue. At the beginning, before setting pressure advance, You set Z to 0.25 (or first layer height). At this point a Voron 2.4 is above the Z homing switch, it's better forst to travel to the starting point and then lower Z to print level. See third line in the code below.

```
M106 S0 ; Set fan speed
SET_VELOCITY_LIMIT ACCEL=4500 ; Set printing acceleration
G0 Z0.25 F9000 ; Move to z height
SET_PRESSURE_ADVANCE ADVANCE=0 ; Set pressure advance

```

**Comment by AndrewEllis93** [comment]
This should now be resolved. Thanks for letting me know.
