### ISSUE TITLE
Gantry Squaring Suggestion

### ISSUE THREAD

**Issue by IRTrail** [AndrewEllis93/Print-Tuning-Guide#46]
During the process of rebuilding my V2, I decided to re-square my gantry. I found the Z locks quite useful:
https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/tallman5/z-locks/

They hold the gantry at a set and even height relative to the frame. They also prevent the gantry from falling if the Z belt is loosened a bit too much.

I also did a squaring with the GE5C mod installed, and this, with the Z locks installed pretty well locks the gantry in place. Thus, just loosen the attach points, and retighten and it is perfect with in an N95/95 tolerance. I wrote about it here:
https://github.com/IRTrail/Voron-Stuff/blob/main/Voron_2_Gantry_Squaring.md

At any rate, the Z locks help, a lot. Just a suggestion.

**Comment by AndrewEllis93** [comment]
Added note in 60efeb5d1b4f70b0bd5f45e1f07b5efe2bf7dde7
