### ISSUE TITLE
small typo (swapped letters)

### ISSUE THREAD

**Issue by cyberhuman** [AndrewEllis93/Print-Tuning-Guide#47]
https://ellis3dp.com/Print-Tuning-Guide/articles/first_layer_squish.html

![image](https://user-images.githubusercontent.com/979624/207041652-8d249194-189d-4489-8784-a9e1f1e616a9.png)

`A_ZDJUST` must `Z_ADJUST`?

**Comment by AndrewEllis93** [comment]
Thank you for letting me know. 
Fixed in abbfe527a321240c0ca31ce821d10ade10ee4c3d.
