### ISSUE TITLE
hyperlinked Amazon product page for BTT Smart Filament Sensor is incorrect

### ISSUE THREAD

**Issue by blkqi** [AndrewEllis93/Print-Tuning-Guide#48]
The hyperlink included in line [pause_resume_filament.md#L64](https://github.com/AndrewEllis93/Print-Tuning-Guide/blame/main/articles/useful_macros/pause_resume_filament.md#L64) forwards the user to the incorrect Amazon product page.

**Comment by AndrewEllis93** [comment]
Good ol' scammy Amazon sellers swapping product info to a new product to keep the old reviews.

I'll fix it

**Comment by AndrewEllis93** [comment]
Fixed this but forgot to close!
