### ISSUE TITLE
Broken PA & EM link?

### ISSUE THREAD

**Issue by millerlarson** [AndrewEllis93/Print-Tuning-Guide#5]
First, thank you for this guide!

I believe the [method](https://github.com/AndrewEllis93/Print-Tuning-Guide#method-2) section has a [broken link](https://github.com/AndrewEllis93/Print-Tuning-Guide#a-note-about-pressure-advance--em) titled "throw you off further." to what is now called [The Relationship Between Pressure Advance & EM](https://github.com/AndrewEllis93/Print-Tuning-Guide#the-relationship-between-pressure-advance--em).

**Comment by AndrewEllis93** [comment]
Resolved in commit 1cb1655ee0351136689da14e2bac67c39b2cb08c - thanks for letting me know!
