### ISSUE TITLE
Pressure advance tool

### ISSUE THREAD

**Issue by chrstrvs** [AndrewEllis93/Print-Tuning-Guide#51]
In the Pressure Advance / Linear Advance Calibration Tool the End G-code doesn't work as intended. When changing to something else than the preset it doesn't take. The generated gcode still contains the preset gcode, which is "PRINT_END ; End macro. Change name to match yours".

**Comment by AndrewEllis93** [comment]
Closing as duplicate of:
https://github.com/AndrewEllis93/Pressure_Linear_Advance_Tool/issues/12

I will look into this
