### ISSUE TITLE
Test pattern prints in the wrong place

### ISSUE THREAD

**Issue by Mark-Dunn-OIL** [AndrewEllis93/Print-Tuning-Guide#57]
I have a voron 0
It has Bed Size X: 120 mm
It has Bed Size Y: 120 mm 
But your test pattern prints outside these dimensions

**Comment by AndrewEllis93** [comment]
Please upload your gcode file

**Comment by Mark-Dunn-OIL** [comment]
Actually it was a website fault. I have blocked cookies for unknown sites.
Websites complying to EU regulation have to request to use cookies and
yours didn't.
Enabling cookies fixed the problem
