### ISSUE TITLE
Question for PA Test

### ISSUE THREAD

**Issue by xenon2008** [AndrewEllis93/Print-Tuning-Guide#63]
Hello together =)

@AndrewEllis93 
First of all, thank you for your wonderful work, I really take my hat off to that - it's unbelievable how much knowledge and time you put into it!

But could you tell me what exactly you mean by that:
_(And then I’d just cover up the slight gapping with single top perimeters - which is unfortunately exclusive to SuperSlicer.)_
[https://ellis3dp.com/Print-Tuning-Guide/articles/pressure_linear_advance/pattern_method.html](https://ellis3dp.com/Print-Tuning-Guide/articles/pressure_linear_advance/pattern_method.html)
Because I can't find this function in superslicer, or I'm just "just" looking for the wrong function or the wrong name

Kindly Regards from Upper Austria =)

**Comment by millerlarson** [comment]
Have a look here:
![image](https://user-images.githubusercontent.com/7883766/218339560-8329cedd-ea93-444b-bb38-c35edd5a98f1.png)

**Comment by xenon2008** [comment]
Ahhh there is it! Thank you so much for this fast Answer ;)  
  
KIndly Regards from Upper Austria
