### ISSUE TITLE
First Layer Squish on delta question

### ISSUE THREAD

**Issue by alexeyzel** [AndrewEllis93/Print-Tuning-Guide#65]
Thank you for very useful guide!

I have a question on first layer squish calibration on delta printer.
I have a Flsun Q5 with Klipper with virtual z endstop (removable probe). After babysteping during test print, I do "Z_OFFSET_APPLY_PROBE" and "SAVE_CONFIG". 
My questions:

- Should I run "DELTA_CALIBRATE" after that with new probe offset value to update position_endstop configuration? If so - should I wait for hotbed to cooldown to room temperature?
- Should I run BED_MESH_CALIBRATE to build new mesh with updated probe z-offset value?

**Comment by AndrewEllis93** [comment]
- I don't have a delta so I can't say with certainty, but from reading about it, it doesn't *sound* like DELTA_CALIBRATE would be necessary after each Z offset change

- IMO you should run a new mesh every print anyway. I'm not a fan of saved meshes, and it avoids these questions entirely. But if using saved meshes, I think it depends if you have `relative_reference_index` set or not.
