### ISSUE TITLE
EM File - Cura Flow

### ISSUE THREAD

**Issue by plano-harry** [AndrewEllis93/Print-Tuning-Guide#68]
I am running the latest version of Cura 5.2.1 for the EM cubes test.  Using the "Settings per Model" option to set each Flow %.  While printing, Fluidd Dashboard is showing a constant 100% for Flow and the console is showing 

**// Unknown command:"EXCLUDE_OBJECT_DEFINE"** (for each of the 21 cubes) 
then a series of 
**// Unknown command:"EXCLUDE_OBJECT_START"
// Unknown command:"EXCLUDE_OBJECT_END"** as it moved to the next cube

Does this mean that I am not getting the expected progression of EM %s?

**Comment by AndrewEllis93** [comment]
You may not have exclude object set up, instructions [here](https://docs.mainsail.xyz/overview/features/exclude-objects)
It should not affect the results of the test however, as long as it's printing successfully
