### ISSUE TITLE
Broken link under section [Tuning	Pressure Advance / Linear Advance	Lines Method (DEPRECATED)]

### ISSUE THREAD

**Issue by Nandox7** [AndrewEllis93/Print-Tuning-Guide#78]
The link to the new tool under page URL bellow is broken.
https://ellis3dp.com/Print-Tuning-Guide/articles/pressure_linear_advance/lines_method_deprecated.html#lines-method-deprecated

**Comment by AndrewEllis93** [comment]
Thanks for letting me know, fixed!
